### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Akalinsky/superhumans_and_cats#1]
Looking mostly good! When I have JavaScript disabled however, I'm able to enter in something like "blah" for the `:year_introducted`, which is then converted to 0. Could you instead try making sure that you only accept valid numbers. Checkout [the `validates_numericality_of` method](http://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_numericality_of) for help with this.

**Comment by Akalinsky** [comment]
Fixed!

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
